# Generated by Django 2.1.4 on 2019-01-09 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190109_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 15, 5, 41, 316393), verbose_name='date published'),
        ),
    ]
