# Generated by Django 2.1.4 on 2019-01-09 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 17, 13, 50, 961215), verbose_name='date published'),
        ),
    ]
