# Generated by Django 2.1.4 on 2019-01-18 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20190117_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 9, 40, 48, 16841), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='page',
            name='first_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 9, 40, 48, 17841)),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 9, 40, 48, 17841)),
        ),
    ]
