# Generated by Django 2.2.4 on 2019-08-22 09:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20190119_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('other', models.IntegerField()),
                ('createTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 17, 29, 23, 883640), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='page',
            name='first_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 17, 29, 23, 883640)),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 17, 29, 23, 883640)),
        ),
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('model1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.Model1')),
                ('address', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'model22',
                'db_tablespace': 'ts',
                'unique_together': {('address', 'mail')},
            },
            bases=('news.model1',),
        ),
        migrations.CreateModel(
            name='Model3',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.model2',),
        ),
        migrations.CreateModel(
            name='Model4',
            fields=[
                ('model2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.Model2')),
                ('name', models.ManyToManyField(to='news.Model1')),
            ],
            bases=('news.model2',),
        ),
    ]
